version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: CI-CD_P2
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: usuarios
    ports:
      - "3306:3306"

  api:
    image: img-api
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    command: ["wait-for-it", "mysql:3306", "-t", "30", "--", "npm", "start"]
    container_name: cont-api
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: usuarios
      DB_PORT: 3306